//
// Home.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Home: Codable {

    public var title: String
    public var _description: String
    public var createdAt: Date

    public init(title: String, _description: String, createdAt: Date) {
        self.title = title
        self._description = _description
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey { 
        case title
        case _description = "description"
        case createdAt = "created_at"
    }

}
