//
// PatchedGroup.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PatchedGroup: Codable {

    public var url: String?
    public var name: String?

    public init(url: String? = nil, name: String? = nil) {
        self.url = url
        self.name = name
    }


}
