//
// Group.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Group: Codable {

    public var url: String
    public var name: String

    public init(url: String, name: String) {
        self.url = url
        self.name = name
    }


}
